<!doctype html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create Repository</title>
    <link rel="stylesheet" href="../../css/mdb.min.css" type="text/css" />
    <link rel="stylesheet" href="../../css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <style>
        .scrollbar::-webkit-scrollbar {
            width: 4px;
            transition: 0.5s;

        }

        .scrollbar::-webkit-scrollbar-thumb {
            background: #3c3c3c;
            border-radius: 3px;
            animation-delay: 0.5s;

        }

        .scrollbar::-webkit-scrollbar-track {
            background: #f4f4f4;
            border-radius: 3px;
            animation-delay: 0.5s;

        }
    </style>

</head>
<body>
<div class="container mt-3">
    <form action="" method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="alert alert-info">
                    <h5 class="alert-heading">Depo Adı</h5>
                    <hr>
                    <p class="mb-0">Depo adı, deponuzun adıdır. Deponuzu tanımlamak için kullanılacak addır. Ayrıca deponuza erişmek için kullanılacak addır. Örneğin, depo adınız "depom" ise, ona şuradan erişeceksiniz: mai/repositoris/depom</p>
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="alert alert-info">
                    <h5 class="alert-heading">Depo Açıklaması</h5>
                    <hr>
                    <p class="mb-0">Depo açıklaması, deponuzun kısa bir açıklamasıdır. Başkalarının deponuzun ne hakkında olduğunu anlamasına yardımcı olmak için kullanılır. Örneğin, deponuz bir projeyle ilgiliyse, projenin ne hakkında olduğunu açıklamak için açıklamayı kullanabilirsiniz.
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="alert alert-info">
                    <h5 class="alert-heading">Depo Türü</h5>
                    <hr>
                    <p class="mb-0">Depo türü, deponuzun türünü belirtir. Depo türü, deponuzun içeriğini belirler. Örneğin, bir proje depo türünü seçerseniz, deponuz bir proje deposu olacaktır. Depo türünü seçmeden önce, depo türlerinin ne anlama geldiğini öğrenmek için <a href="../../docs/repositorys">dökümanları</a> inceleyin.
                </div>
            </div>
            <div class="col-md-6">
                <div class="alert alert-warning">
                    <h5 class="alert-heading">Depo Görünürlüğü</h5>
                    <hr>
                    <p class="mb-0">Depo görünürlüğü, deponuzun görünürlüğünü belirtir. Depo görünürlüğü, deponuzun kimler tarafından görülebileceğini belirler. Örneğin, herkes için görünür seçerseniz, deponuz herkes tarafından görülebilir. Depo görünürlüğünü seçmeden önce, depo görünürlüğünün ne anlama geldiğini öğrenmek için <a href="../../docs/repositorys">dökümanları</a> inceleyin.
                </div>
            </div>
            <div class="col-md-6">
                <div class="alert alert-warning">
                    <h5 class="alert-heading">Depo Lisansı</h5>
                    <hr>
                    <p class="mb-0">Depo lisansı, deponuzun lisansını belirtir. Depo lisansı, deponuzun kimler tarafından kullanılabileceğini belirler. Örneğin, MIT lisansı seçerseniz, deponuz herkes tarafından kullanılabilir. Depo lisansını seçmeden önce, depo lisansının ne anlama geldiğini öğrenmek için <a href="../../docs/repositorys">dökümanları</a> inceleyin.
                </div>
            </div>
            <div class="col-md-6">
                <div class="alert alert-warning">
                    <h5 class="alert-heading">Depo Dili</h5>
                    <hr>
                    <p class="mb-0">Depo dili, deponuzun dili belirtir. Depo dili, deponuzun hangi dili kullandığını belirler. Örneğin, C# dili seçerseniz, deponuz C# dili kullanılarak yazılmıştır. Depo dili seçmeden önce, depo dili ne anlama geldiğini öğrenmek için <a href="../../docs/repositorys">dökümanları</a> inceleyin.
                </div>
            </div>
        </div>
    </form>
</div>
<script src="../../js/mdb.min.js"></script>
</body>
</html>